# 构建和部署Jekyll网站到GitHub Pages的示例工作流程
名称：部署 Jekyll 并预安装 GitHub Pages 依赖项

在:
  # 在推送目标为默认分支时运行
  推:
    分支：["main"]

  # 允许您从操作选项卡手动运行此工作流程
  工作流派送:

# 设置 GITHUB_TOKEN 的权限以允许部署到 GitHub Pages
权限:
  目录: 阅读
  页: 写
  id-token：写

# 仅允许一个并发部署，跳过在进行中的运行和最新排队之间的排队运行。
# 但是，请不要取消正在进行的运行，因为我们希望允许这些生产部署完成。
并发:
  组: "页面"
  取消进行中： false

工作:
  # 构建作业
  构建:
    运行于：ubuntu-latest
    步骤:
      - 名称: 结账
        使用： actions/checkout@v4
      - 名称: 设置页面
        使用：actions/configure-pages@v5
      - 名称: 使用 Jekyll 构建
        使用：actions/jekyll-build-pages@v1
        与：
          源: ./
          目标：./_site
      - 名称: 上传工件
        使用：actions/upload-pages-artifact@v3

  # 部署工作
  部署:
    环境:
      名称: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    运行于：ubuntu-latest
    需要： 构建
    步骤:
      - 名称: 部署到GitHub Pages
        id： 部署
        使用：actions/deploy-pages@v4
